"""empty message

Revision ID: 230f12e4e0b8
Revises: 
Create Date: 2026-03-27 12:38:09.882768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '230f12e4e0b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
