"""empty message

Revision ID: 586f59020ffe
Revises: 982569caf9dd
Create Date: 2026-03-27 21:06:34.212030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '586f59020ffe'
down_revision = '982569caf9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
