"""empty message

Revision ID: 982569caf9dd
Revises: 230f12e4e0b8
Create Date: 2026-03-27 16:45:30.880183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982569caf9dd'
down_revision = '230f12e4e0b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    # ### end Alembic commands ###
